//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Queries.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Arrows] (
        ///    [Id]         BIGINT       NOT NULL,
        ///    [Owner]      BIGINT       NOT NULL,
        ///    [Label]      VARCHAR (50) NOT NULL,
        ///    [From]       BIGINT       NOT NULL,
        ///    [To]         BIGINT       NOT NULL,
        ///    [Width]      FLOAT (53)   NOT NULL,
        ///    [Height]     FLOAT (53)   NOT NULL,
        ///    [X]          FLOAT (53)   NOT NULL,
        ///    [Y]          FLOAT (53)   NOT NULL,
        ///    [Foreground] INT          NOT NULL,
        ///    [Background] INT          NOT NULL
        ///).
        /// </summary>
        internal static string CreateArrowTable {
            get {
                return ResourceManager.GetString("CreateArrowTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Concept] (
        ///    [Id]         BIGINT       NOT NULL,
        ///    [Owner]      BIGINT       NOT NULL,
        ///    [Label]      VARCHAR (50) NOT NULL,
        ///    [Width]      FLOAT (53)   NOT NULL,
        ///    [Height]     FLOAT (53)   NOT NULL,
        ///    [X]          FLOAT (53)   NOT NULL,
        ///    [Y]          FLOAT (53)   NOT NULL,
        ///    [Foreground] INT          NOT NULL,
        ///    [Background] INT          NOT NULL
        ///).
        /// </summary>
        internal static string CreateConceptTable {
            get {
                return ResourceManager.GetString("CreateConceptTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Relation] (
        ///    [Id]         BIGINT       NOT NULL,
        ///    [Owner]      BIGINT       NOT NULL,
        ///    [Label]      VARCHAR (50) NOT NULL,
        ///    [Width]      FLOAT (53)   NOT NULL,
        ///    [Height]     FLOAT (53)   NOT NULL,
        ///    [X]          FLOAT (53)   NOT NULL,
        ///    [Y]          FLOAT (53)   NOT NULL,
        ///    [Foreground] INT          NOT NULL,
        ///    [Background] INT          NOT NULL
        ///).
        /// </summary>
        internal static string CreateRelationTable {
            get {
                return ResourceManager.GetString("CreateRelationTable", resourceCulture);
            }
        }
    }
}
